obj-y += service/wechat_service.o

obj-y += MmBp_Embedded_1.0.4/crc32/crc32.o
obj-y += MmBp_Embedded_1.0.4/protobuf/epb.o
obj-y += MmBp_Embedded_1.0.4/protobuf/epb_MmBp.o

obj-y += MmBp_helper/wechat_protocol.o
